// DO NOT EDIT THIS FILE, EDIT THE WEBPACK COMMON CONFIG INSTEAD, WHICH WILL MODIFY THIS FILE
let _DEBUG_INFO_ENABLED = true; // This value will be overwritten by webpack
/* @toreplace VERSION */
/* @toreplace DEBUG_INFO_ENABLED */
export const APP_NAME = 'process.env.APP_NAME';
export const UPDATED_DATE = 'process.env.UPDATED_DATE';
export const VERSION = 'process.env.VERSION';
export const DEBUG_INFO_ENABLED = '_DEBUG_INFO_ENABLED';
export const SERVER_API_URL = 'process.env.SERVER_API_URL';
export const BUILD_TIMESTAMP = 'process.env.BUILD_TIMESTAMP';
